# Generated by Django 3.2.25 on 2025-06-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
