# Generated by Django 3.2.25 on 2025-06-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250626_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='año',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('acción', 'Acción'), ('romance', 'Romance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
