# Generated by Django 3.2.25 on 2025-06-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250626_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Comedia', 'Comedia'), ('Terror', 'Terror'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Acción', 'Acción'), ('Animación', 'Animación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(),
        ),
    ]
