# Generated by Django 3.2.25 on 2025-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250628_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('comedia', 'Comedia'), ('drama', 'Drama'), ('accion', 'Acción'), ('romance', 'Romance'), ('terror', 'Terror')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
